language: python
python:
        - "3.5"

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y redis-server

install: "pip install -e ."

script: python setup.py -q test

notifications:
      slack: a-maze-team:KQAj1tr2neVDB38uGAQFcuA9
